GO_EASY_ON_ME=1
include theos/makefiles/common.mk

APPLICATION_NAME = Loader
TOOL_NAME = Bootstrap
Loader_FILES = main.m Callback.m MemLoaderOperation.m LoaderAppDelegate.mm LoaderVC.m
Bootstrap_FILES = Bootstrap.m
Bootstrap_INSTALL_PATH = /Applications/Loader.app/

include $(FW_MAKEDIR)/application.mk
include $(FW_MAKEDIR)/tool.mk
